<?php


/**
 * Created by PhpStorm.
 * User: AdminRus
 * Date: 21.04.2017
 * Time: 21:53
 */
namespace app\controllers\action;
use yii\web\ErrorAction;
class MyerrorAction extends ErrorAction
{
    public function init()
    {
        //$this->layout=false;
        parent::init(); // TODO: Change the autogenerated stub
    }

}