<?php

/**
 * Created by PhpStorm.
 * User: AdminRus
 * Date: 05.04.2017
 * Time: 22:02
 */
namespace app\components;
use yii\base\Widget;
use app\models\Category;
use Yii;
class MenuWidget extends Widget
{
    public $tpl;
    public $model;
    public $data;
    public $tree;
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl===null){
            $this->tpl='menu';
        }
        $this->tpl.='.php';
    }

    public function  run()
    {
        if($this->tpl=='menu.php'){
            $menuss=Yii::$app->cache->get('category_menu');
            if ($menuss) return $menuss;
        }

        $this->data=Category::find()->indexBy('id')->asArray()->all();
        $this->tree=$this->getTree();
        $this->menuHtml=$this->getMenuHtml($this->tree);

        if($this->tpl=='menu.php'){
            Yii::$app->cache->set('categoty_menu',$this->menuHtml, 120);
        }
        return $this->menuHtml;
    }

    public function getTree(){
        $tree=[];
        foreach ($this->data as $id=>&$node){
            if(!$node['parent_id'])
                $tree[$id]=&$node;
            else
                $this->data[$node['parent_id']]['childs'][$node['id']]=&$node;
        }
        return $tree;
    }

    protected function getMenuHtml($tree,$tab=''){
        $str='';
        foreach($tree as $category){
            $str.=$this->catToTemplate($category,$tab);
        }
        return $str;
    }

    protected function catToTemplate($category,$tab){
        ob_start();
        include __DIR__.'/menu_tpl/'.$this->tpl;
        return ob_get_clean();
    }
}